### ISSUE TITLE
Add a rust linter

### ISSUE THREAD

**Issue by birdsarah** [mozilla-services/cjms#15]
@jswinarton you appear to be using a rust linter that I'm not. This is great. What are you using? Do you know if we can enforce it?

**Comment by jswinarton** [comment]
Hey, I actually wasn't using one. I just have some defaults set in vscode that strips out whitespace at the end of a line and ensures there is a newline at the end of the file, which is probably what you saw on my PR. But I am in favour of using clippy for sure. I haven't used it myself so I can't offer much by way of comments but I'm happy it's there.

**Comment by birdsarah** [comment]
Closed via #16
